WITH CUSTOMER  AS (
select 	C_CUSTOMER_SK ,	C_CUSTOMER_ID ,	C_CURRENT_CDEMO_SK ,C_CURRENT_HDEMO_SK ,
	C_CURRENT_ADDR_SK ,
	C_FIRST_SHIPTO_DATE_SK ,
	C_FIRST_SALES_DATE_SK ,
	C_SALUTATION ,
	C_FIRST_NAME ,
	C_LAST_NAME ,
	C_PREFERRED_CUST_FLAG from DBTDB.PUBLIC.CUSTOMER 
)
SELECT * FROM CUSTOMER ;
